spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/vacation.project
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: rkdlem48@gmail.com
    password: 4815592kim!!
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
  config: classpath:log4j2.yml

